- draft-tschofenig-rats-psa-token.md
Add Simon text re: verification considerations as per discussion with
Adrian
> add verification considerations

- draft-tschofenig-rats-psa-token.md
> add xclaim to the list of implementations

- draft-tschofenig-rats-psa-token.md
> Update CBOR ref

- draft-tschofenig-rats-psa-token.md
> say that the Verifier obtains the keys from an Endorser

- cddl/test/FAIL_ImplementationID_missing.diag
- cddl/test/FAIL_ImplementationID_wrong_format.diag
- cddl/test/FAIL_InstanceID_missing.diag
- cddl/test/FAIL_InstanceID_wrong_format.diag
- cddl/test/FAIL_SoftwareComponent_Measurement_missing.diag
- cddl/test/FAIL_SoftwareComponent_and_NoSwMeasurements.diag
- cddl/test/GOOD_full.diag
- cddl/test/GOOD_mandatory_only.diag
- draft-tschofenig-rats-psa-token.md
> Drop debris of partition id

- draft-tschofenig-rats-psa-token.md
Workaround for the e-mail SPF issue in #51
> Update Adrian's e-mail address

- draft-tschofenig-rats-psa-token.md
Possible edits to be incorporated in the future.
> Small updates

- cddl/psa-boot-seed.cddl
- cddl/psa-token.cddl
- cddl/test/FAIL_BootSeed_too_big.diag
- cddl/test/FAIL_BootSeed_too_small.diag
- draft-tschofenig-rats-psa-token.md
> make boot-seed optional and variable length

- draft-tschofenig-rats-psa-token.md
> wordsmithing around the verification service indication claim definition

- .github/workflows/archive.yml
- .github/workflows/ghpages.yml
- .github/workflows/publish.yml
- .github/workflows/update.yml
- Gemfile
- Makefile
- cddl/Makefile
- draft-tschofenig-rats-psa-token.md
> build improvements

- draft-tschofenig-rats-psa-token.md
> RECOMMEND using RFC9053 algorithms

- draft-tschofenig-rats-psa-token.md
> Update ref to the RATS architecture RFC

- draft-tschofenig-rats-psa-token.md
Update URL for Firmware Framework doc per Issue #82 
Fixes #82
> Fix FF URL  for Issue 82

- draft-tschofenig-rats-psa-token.md
> A crack at defining initial attestation

- draft-tschofenig-rats-psa-token.md
> scalability considerations

- draft-tschofenig-rats-psa-token.md
> disallow DEBs

- draft-tschofenig-rats-psa-token.md
> do not require CBOR preferred encoding

- draft-tschofenig-rats-psa-token.md
> say that Sign1 and Mac0 are tagged

- draft-tschofenig-rats-psa-token.md
Either add a reference or omit the mechanisms.
I would not even go into a discussion about CRLs and OCSP in this context
> Remove mention of CRLs and OCSP

- draft-tschofenig-rats-psa-token.md
Added a reference to the RATS architecture regarding terminology
> Terminology

- draft-tschofenig-rats-psa-token.md
In a philologically pure interpretation of the RATS architecture, each target environment “object” in Figure 1 (i.e., updateable PRoT, ARoT, etc.) is a different target environment because it is separately measured.
> one or more TEs

- draft-tschofenig-rats-psa-token.md
> Update PSA references

- draft-tschofenig-rats-psa-token.md
> Move content from abstract to intro as suggested by Eliot

- draft-tschofenig-rats-psa-token.md
> Adding the term "secure enclave" to the terminology section

- draft-tschofenig-rats-psa-token.md
> Use _CONFIG instead of -cfg for configuration payloads labels
